minimum_pre_commit_version: 3.1.0
default_stages: [commit, push]
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: debug-statements
    -   id: double-quote-string-fixer
    -   id: name-tests-test
    -   id: requirements-txt-fixer
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]
        files: \.py$
-   repo: https://github.com/asottile/add-trailing-comma
    rev: v2.4.0
    hooks:
    -   id: add-trailing-comma
        args: [--py36-plus]
        files: \.py$
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v2.0.1
    hooks:
    -   id: autopep8
        files: \.py$
-   repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        args: ["--max-line-length=120", "--ignore=D100,D104,E203,E402,E501,W503", "--docstring-convention=google"]
        files: \.py$
-   repo: https://github.com/PyCQA/autoflake
    rev: v2.0.1
    hooks:
    -   id: autoflake
        args: ["--in-place", "--remove-all-unused-imports", "--remove-unused-variables", "--expand-star-imports", "--ignore-init-module-imports"]
        files: \.py$
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.0.1
    hooks:
    -   id: mypy
        additional_dependencies: [types-all]
        files: \.py$
-   repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
    -   id: black
        args: ["--line-length=120"]
        files: \.py$
-   repo: local
    hooks:
    -   id: pytest
        name: pytest
        entry: pytest -m "not performance"
        language: system
        pass_filenames: false
        stages: [commit, push]
