minimum_pre_commit_version: 3.1.0
default_stages: [commit, push]
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: debug-statements
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]
        files: \.py$
-   repo: https://github.com/asottile/add-trailing-comma
    rev: v2.4.0
    hooks:
    -   id: add-trailing-comma
        args: [--py36-plus]
        files: \.py$
-   repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        args: ["--max-line-length=120", "--ignore=D100,D104,E203,E402,E501,W503"]
        files: \.py$
-   repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
    -   id: black
        args: ["--line-length=120"]
        files: \.py$
-   repo: local
    hooks:
    - id: requirements.txt
      name: requirements.txt
      entry: bash -c 'poetry export -f requirements.txt --output requirements.txt'
      language: system
    - id: requirements_dev.txt
      name: requirements_dev.txt
      entry: bash -c 'poetry export -f requirements.txt --output requirements_dev.txt --with dev'
      language: system
