name: python-dependencies-tests-pre-commit

on:
  push:
    branches: [dev]
  pull_request:
    branches: [master]

jobs:
  poetry:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - uses: actions/checkout@v3
        with:
          path: dev
      - name: Setup Poetry
        uses: .github/actions/setup-poetry
