name: docs-build-publish

on:
  release:
    types: [ published ]

jobs:
  docs-build-publish:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Setup Poetry
        uses: ./.github/workflows/actions/setup-poetry

      - name: Deploy Mkdocs
        run: mkdocs gh-deploy

      - name: Building Package Distributions
        run: poetry build

      - name: Publish PyPi package
        uses: code-specialist/pypi-poetry-publish@v1
        with:
          BRANCH: "master"
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_REGISTRY_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
          PUBLISH_REGISTRY_USERNAME: "__token__"
          PACKAGE_DIRECTORY: "./src/"
          PUBLISH_REGISTRY: "https://test.pypi.org/simple/"
          POETRY_VERSION: "1.3.2"
          POETRY_CORE_VERSION: "1.4.0"



#      - name: Publish Package to PyPi
#        run: poetry publish
        # https://github.com/marketplace/actions/pypi-poetry-publish
#        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
#        uses: pypa/gh-action-pypi-publish@release/v1
#        with:
#          password: ${{ secrets.PYPI_API_TOKEN }}
