name: Package

on:
  pull_request:
    branches: [master]

jobs:
  publish_package:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Setup Poetry
        uses: LouisdeBruijn/waterfall-logging/.github/workflows/reusable-workflow.yml@dev

      - name: Deploy Mkdocs
        run: mkdocs gh-deploy

      - name: Building Package Distributions
        run: poetry build

      - name: Publish Package to PyPi
        run: poetry publish
#        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
#        uses: pypa/gh-action-pypi-publish@release/v1
#        with:
#          password: ${{ secrets.PYPI_API_TOKEN }}
